name: Publish to GitHub

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Publish WPF app
        working-directory: ./src/RqCalc.WpfApp
        run: dotnet publish -c Release -o publish

      - name: Create zip archive
        working-directory: ./src/RqCalc.WpfApp/publish
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $patterns = '*.dll','*.exe','*.json','rqdata.sqlite'
          $files = foreach ($pattern in $patterns) { Get-ChildItem -Path . -Filter $pattern -File }
          Compress-Archive -Path $files.FullName -Destination RqCalc.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./src/RqCalc.WpfApp/publish/RqCalc.zip
